# -*- encoding : utf-8 -*-
module Qw3common
  module Generators
    class IconsGenerator < Rails::Generators::Base
      
      source_root File.expand_path("../templates", __FILE__)
      
      def create_icons_files
        #imagens pequenas
        copy_file "assets/images/icons/documents/small/bmp_file.png", "public/images/icons/documents/small/bmp_file.png"
        copy_file "assets/images/icons/documents/small/css_file.png", "public/images/icons/documents/small/css_file.png"
        copy_file "assets/images/icons/documents/small/csv_file.png", "public/images/icons/documents/small/csv_file.png"
        copy_file "assets/images/icons/documents/small/doc_file.png", "public/images/icons/documents/small/doc_file.png"
        copy_file "assets/images/icons/documents/small/doc_file.png", "public/images/icons/documents/small/docx_file.png"
        copy_file "assets/images/icons/documents/small/eps_file.png", "public/images/icons/documents/small/eps_file.png"
        copy_file "assets/images/icons/documents/small/gif_file.png", "public/images/icons/documents/small/gif_file.png"
        copy_file "assets/images/icons/documents/small/html_file.png", "public/images/icons/documents/small/html_file.png"
        copy_file "assets/images/icons/documents/small/ico_file.png", "public/images/icons/documents/small/ico_file.png"
        copy_file "assets/images/icons/documents/small/jpg_file.png", "public/images/icons/documents/small/jpg_file.png"
        copy_file "assets/images/icons/documents/small/js_file.png", "public/images/icons/documents/small/js_file.png"
        copy_file "assets/images/icons/documents/small/json_file.png", "public/images/icons/documents/small/json_file.png"
        copy_file "assets/images/icons/documents/small/mp3_file.png", "public/images/icons/documents/small/mp3_file.png"
        copy_file "assets/images/icons/documents/small/pdf_file.png", "public/images/icons/documents/small/pdf_file.png"
        copy_file "assets/images/icons/documents/small/php_file.png", "public/images/icons/documents/small/php_file.png"
        copy_file "assets/images/icons/documents/small/png_file.png", "public/images/icons/documents/small/png_file.png"
        copy_file "assets/images/icons/documents/small/ppt_file.png", "public/images/icons/documents/small/ppt_file.png"
        copy_file "assets/images/icons/documents/small/ppt_file.png", "public/images/icons/documents/small/pptx_file.png"
        copy_file "assets/images/icons/documents/small/psd_file.png", "public/images/icons/documents/small/psd_file.png"
        copy_file "assets/images/icons/documents/small/svg_file.png", "public/images/icons/documents/small/svg_file.png"
        copy_file "assets/images/icons/documents/small/swf_file.png", "public/images/icons/documents/small/swf_file.png"
        copy_file "assets/images/icons/documents/small/tiff_file.png", "public/images/icons/documents/small/tiff_file.png"
        copy_file "assets/images/icons/documents/small/txt_file.png", "public/images/icons/documents/small/txt_file.png"
        copy_file "assets/images/icons/documents/small/wav_file.png", "public/images/icons/documents/small/wav_file.png"
        copy_file "assets/images/icons/documents/small/xls_file.png", "public/images/icons/documents/small/xls_file.png"
        copy_file "assets/images/icons/documents/small/xls_file.png", "public/images/icons/documents/small/xlsx_file.png"
        copy_file "assets/images/icons/documents/small/xml_file.png", "public/images/icons/documents/small/xml_file.png"
        
        #imagens médias
        copy_file "assets/images/icons/documents/medium/bmp_file.png", "public/images/icons/documents/medium/bmp_file.png"
        copy_file "assets/images/icons/documents/medium/css_file.png", "public/images/icons/documents/medium/css_file.png"
        copy_file "assets/images/icons/documents/medium/csv_file.png", "public/images/icons/documents/medium/csv_file.png"
        copy_file "assets/images/icons/documents/medium/doc_file.png", "public/images/icons/documents/medium/doc_file.png"
        copy_file "assets/images/icons/documents/medium/doc_file.png", "public/images/icons/documents/medium/docx_file.png"
        copy_file "assets/images/icons/documents/medium/eps_file.png", "public/images/icons/documents/medium/eps_file.png"
        copy_file "assets/images/icons/documents/medium/gif_file.png", "public/images/icons/documents/medium/gif_file.png"
        copy_file "assets/images/icons/documents/medium/html_file.png", "public/images/icons/documents/medium/html_file.png"
        copy_file "assets/images/icons/documents/medium/ico_file.png", "public/images/icons/documents/medium/ico_file.png"
        copy_file "assets/images/icons/documents/medium/jpg_file.png", "public/images/icons/documents/medium/jpg_file.png"
        copy_file "assets/images/icons/documents/medium/js_file.png", "public/images/icons/documents/medium/js_file.png"
        copy_file "assets/images/icons/documents/medium/json_file.png", "public/images/icons/documents/medium/json_file.png"
        copy_file "assets/images/icons/documents/medium/mp3_file.png", "public/images/icons/documents/medium/mp3_file.png"
        copy_file "assets/images/icons/documents/medium/pdf_file.png", "public/images/icons/documents/medium/pdf_file.png"
        copy_file "assets/images/icons/documents/medium/php_file.png", "public/images/icons/documents/medium/php_file.png"
        copy_file "assets/images/icons/documents/medium/png_file.png", "public/images/icons/documents/medium/png_file.png"
        copy_file "assets/images/icons/documents/medium/ppt_file.png", "public/images/icons/documents/medium/ppt_file.png"
        copy_file "assets/images/icons/documents/medium/ppt_file.png", "public/images/icons/documents/medium/pptx_file.png"
        copy_file "assets/images/icons/documents/medium/psd_file.png", "public/images/icons/documents/medium/psd_file.png"
        copy_file "assets/images/icons/documents/medium/svg_file.png", "public/images/icons/documents/medium/svg_file.png"
        copy_file "assets/images/icons/documents/medium/swf_file.png", "public/images/icons/documents/medium/swf_file.png"
        copy_file "assets/images/icons/documents/medium/tiff_file.png", "public/images/icons/documents/medium/tiff_file.png"
        copy_file "assets/images/icons/documents/medium/txt_file.png", "public/images/icons/documents/medium/txt_file.png"
        copy_file "assets/images/icons/documents/medium/wav_file.png", "public/images/icons/documents/medium/wav_file.png"
        copy_file "assets/images/icons/documents/medium/xls_file.png", "public/images/icons/documents/medium/xls_file.png"
        copy_file "assets/images/icons/documents/medium/xls_file.png", "public/images/icons/documents/medium/xlsx_file.png"
        copy_file "assets/images/icons/documents/medium/xml_file.png", "public/images/icons/documents/medium/xml_file.png"
        
        #imagens grandes
        copy_file "assets/images/icons/documents/big/bmp_file.png", "public/images/icons/documents/big/bmp_file.png"
        copy_file "assets/images/icons/documents/big/css_file.png", "public/images/icons/documents/big/css_file.png"
        copy_file "assets/images/icons/documents/big/csv_file.png", "public/images/icons/documents/big/csv_file.png"
        copy_file "assets/images/icons/documents/big/doc_file.png", "public/images/icons/documents/big/doc_file.png"
        copy_file "assets/images/icons/documents/big/doc_file.png", "public/images/icons/documents/big/docx_file.png"
        copy_file "assets/images/icons/documents/big/eps_file.png", "public/images/icons/documents/big/eps_file.png"
        copy_file "assets/images/icons/documents/big/gif_file.png", "public/images/icons/documents/big/gif_file.png"
        copy_file "assets/images/icons/documents/big/html_file.png", "public/images/icons/documents/big/html_file.png"
        copy_file "assets/images/icons/documents/big/ico_file.png", "public/images/icons/documents/big/ico_file.png"
        copy_file "assets/images/icons/documents/big/jpg_file.png", "public/images/icons/documents/big/jpg_file.png"
        copy_file "assets/images/icons/documents/big/js_file.png", "public/images/icons/documents/big/js_file.png"
        copy_file "assets/images/icons/documents/big/json_file.png", "public/images/icons/documents/big/json_file.png"
        copy_file "assets/images/icons/documents/big/mp3_file.png", "public/images/icons/documents/big/mp3_file.png"
        copy_file "assets/images/icons/documents/big/pdf_file.png", "public/images/icons/documents/big/pdf_file.png"
        copy_file "assets/images/icons/documents/big/php_file.png", "public/images/icons/documents/big/php_file.png"
        copy_file "assets/images/icons/documents/big/png_file.png", "public/images/icons/documents/big/png_file.png"
        copy_file "assets/images/icons/documents/big/ppt_file.png", "public/images/icons/documents/big/ppt_file.png"
        copy_file "assets/images/icons/documents/big/ppt_file.png", "public/images/icons/documents/big/pptx_file.png"
        copy_file "assets/images/icons/documents/big/psd_file.png", "public/images/icons/documents/big/psd_file.png"
        copy_file "assets/images/icons/documents/big/svg_file.png", "public/images/icons/documents/big/svg_file.png"
        copy_file "assets/images/icons/documents/big/swf_file.png", "public/images/icons/documents/big/swf_file.png"
        copy_file "assets/images/icons/documents/big/tiff_file.png", "public/images/icons/documents/big/tiff_file.png"
        copy_file "assets/images/icons/documents/big/txt_file.png", "public/images/icons/documents/big/txt_file.png"
        copy_file "assets/images/icons/documents/big/wav_file.png", "public/images/icons/documents/big/wav_file.png"
        copy_file "assets/images/icons/documents/big/xls_file.png", "public/images/icons/documents/big/xls_file.png"
        copy_file "assets/images/icons/documents/big/xls_file.png", "public/images/icons/documents/big/xlsx_file.png"
        copy_file "assets/images/icons/documents/big/xml_file.png", "public/images/icons/documents/big/xml_file.png"
      end
      
    end
  end
end
